M48
; DRILL file {KiCad (6.0.4)} date Thu Sep  8 18:29:42 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-08T18:29:42-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X165.1Y-83.31
X165.1Y-91.29
T2
X82.73Y-79.63
X82.73Y-123.43
X124.98Y-79.7
X124.98Y-123.5
X166.65Y-123.5
T0
M30
